import mongoose,{Schema} from "mongoose";

const userSchema = new Schema({
      userName:{
        type:String,
        required:true,
        unique:true
      },
      fullName:{
        type:String,
        required:true,
      },
      password:{
        type:String,
        required:true,
        length:6
      },
      email:{
        type:String,
        required:true,
        unique:true
      },
      followers:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'User',
            default:[],
        }
      ],
      following:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:'User',
            default:[],
        }
      ],
      profileImage:{
        type:String,
        default:""
      },
      coverImage:{
        type:String,
        default:""
      },
      bio:{
        type:String,
        default:""
      },
      link:{
        type:String,
        default:""
      },
      likedposts:[
        {
          type:mongoose.Schema.Types.ObjectId,
          ref:'Post'
        }
      ]
},{timestamps:true})

export const User = mongoose.model('Users',userSchema);